### PR TITLE
Chore: Add Contributing.md and semantic-release config

### PR DESCRIPTION
**Pull request by okonet**
This PR automates the release process for new versions. It uses semantic-release with [ESLint commit message conventions](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint)

### CODE REVIEW

**Comment by okonet** [comment]
@vieira can you please add `secrets.GITHUB_TOKEN` and `secrets.NPM_TOKEN` to actions? I don't have enough permissions for that.

**Comment by okonet** [comment]
Hmm, also `- Workflows can't be executed on this repository. Please check your payment method or billing status.` doesn't sound right. Maybe it needs some additional action to be activated?

**Comment by vieira** [comment]
Hello @okonet,

Done! The github token, however, is under `GH_TOKEN` as the name `GITHUB_TOKEN` seems to be invalid:

Screen Shot 2019-12-19 at 21 01 33

**Comment by okonet** [comment]
Just run the workflow. Seems to be working. Let's try merging and cutting a new release using it!

**Comment by okonet** [comment]
@vieira weird, all documentation I can find refers to `GITHUB_TOKEN` and that's what I have on my local machine as well. Are you sure everything fine with the setup?

**Comment by vieira** [comment]
Not entirely sure. I saw in the readme at [semantic-release/github](https://github.com/semantic-release/github) that the variable could be named `GH_TOKEN` or `GITHUB_TOKEN`. So as `GITHUB_TOKEN` gave that error I tried with `GH_TOKEN` which seemed to work.

Screen Shot 2019-12-19 at 21 28 58

Is this the right place?

**Comment by okonet** [comment]
yes, I'll need to adapt the script then. Still trying :)

**Pull request merged**
