### PR TITLE
Experimental support for color temperature

### PR DESCRIPTION
**Pull request by vieira**
Adds experimental support for controlling color temperature via the `set_ct_abx` operation on supported devices. Previously only devices supporting `color` would be able to set the color temperature.

### CODE REVIEW

**Comment by vieira** [comment]
Should resolve #17 and #22.

**Comment by iChUdY** [comment]
Hi,

CT message works. But temperaure selector in home app is missing cold color temperature screenshot 1,2. And some issue with switching color in screenshot 3. When I press the color so the color of the bulb changes but no in home app.

c134ec6e-4673-4918-b11b-07abaeda8676
3a9126c0-2130-460d-b7e0-d396c1bedf8e
20669a72-625b-4a80-9a1d-fd2713e55b74

**Comment by patiw** [comment]
Hi, when would you like to merge those changes?

**Comment by iChUdY** [comment]
This is experimental support.. need some fix, tests then merge.

**Comment by patiw** [comment]
Is there an easy option I can install this for my homebridge so I can test it also? Sorry if those are dumb questions but I'm not familiar with JS and new to homebridge stuff.

**Comment by J7mbo** [comment]
Hey @vieira - anything I can do to help with this? Or is it closed because we’ll no longer be supporting it?

**Comment by vieira** [comment]
@J7mbo I will push an update today or tomorrow that should implement color temperature for all yeelight wifi devices that support it.

However after facing many issues when declaring both color and color temperature and failing to have it work without glitches I read the Homekit documentation and realized that Homekit does not support that a color temperature characteristic is added to a lightbulb supporting color:

> 8.107 Color Temperature:
> (...)
> If this characteristic is included in the Lightbulb (page 217), Hue (page 151) and Saturation (page 159) must not be included as optional characteristics in Lightbulb (page 217).
> This characteristic must not be used for lamps which support color.

To comply with the Homekit specification I will not be adding this to color bulbs. Note that Home will still allow you to define the color temperature for your color bulbs (as always), but it sends the device a color code (HSV), not a color temperature (mired/K).

Let me know if you have any questions/concerns.

**Comment by vieira** [comment]
I have just released a beta version with color temperature support. It can be installed with `npm install -g homebridge-yeelight-wifi@beta`.

The file `accessories/cachedAccessories` **must be removed** before starting the new version.

**Comment by vieira** [comment]
@J7mbo Were you able to test the beta on your tunable white bulbs? Does it work as expected?

**Pull request closed without merging**
